import React from "react";
import Navbar from "../landingpages/Navbar";
import Footer from "../landingpages/Footer";

const OcrEngine = () => {
  return (
    <div>
      <Navbar />
      <div className="w-full px-4 sm:px-6 lg:px-30 xl:px-50 py-5 lg:py-10">
        <h1 className="font-['Kollektif'] font-bold text-[20px] sm:text-[22px] lg:text-[24px] leading-[100%] tracking-[0.02em] text-[#21527D] mb-3 sm:mb-4">
          OCR Engine
        </h1>

        <p className="font-['Avenir_LT_Std'] font-[350] text-[14px] sm:text-[15px] lg:text-[16px] leading-[26px] sm:leading-[28px] lg:leading-[30px] tracking-[0.06em] text-black mb-4">
          Clario’s OCR Engine is built as a foundational intelligence layer
          rather than a simple text capture utility. At its core, the engine is
          designed to convert unstructured visual data into structured,
          machine-readable intelligence that can be consumed across systems,
          workflows, and decision layers. Unlike traditional OCR systems that
          stop at character recognition, Clario’s engine focuses on semantic
          understanding, layout preservation, and context reconstruction. This
          ensures that extracted data is not only accurate but also immediately
          usable for downstream automation and analytics.
        </p>

        <p className="font-['Avenir_LT_Std'] font-[350] text-[14px] sm:text-[15px] lg:text-[16px] leading-[26px] sm:leading-[28px] lg:leading-[30px] tracking-[0.06em] text-black mb-4">
          The engine supports a wide range of document formats, including
          scanned PDFs, native PDFs, images captured via mobile devices, and
          multi-page documents generated by legacy systems. It is optimized to
          handle real-world data imperfections such as skewed scans,
          low-resolution images, inconsistent fonts, watermarks, stamps, and
          background noise. Through adaptive preprocessing pipelines, the engine
          dynamically enhances document quality before extraction, reducing
          dependency on manual cleanup or reprocessing.
        </p>

        <p className="font-['Avenir_LT_Std'] font-[350] text-[14px] sm:text-[15px] lg:text-[16px] leading-[26px] sm:leading-[28px] lg:leading-[30px] tracking-[0.06em] text-black mb-4">
          What differentiates Clario’s OCR Engine is its ability to learn
          continuously. The system leverages feedback loops where corrected
          outputs can be reintegrated into the model, allowing accuracy to
          improve over time without retraining from scratch. This makes it
          particularly effective in high-volume environments where document
          structures evolve gradually rather than changing overnight.
          Enterprises benefit from a system that adapts to operational reality
          instead of forcing rigid templates.
        </p>

        <p className="font-['Avenir_LT_Std'] font-[350] text-[14px] sm:text-[15px] lg:text-[16px] leading-[26px] sm:leading-[28px] lg:leading-[30px] tracking-[0.06em] text-black mb-4">
          From a scalability standpoint, the engine is architected for both
          batch and real-time processing. Whether processing millions of
          archival documents or extracting data from live uploads through APIs,
          the engine maintains consistent performance and reliability. It
          supports horizontal scaling, ensuring that increased document volumes
          do not compromise latency or accuracy. This makes it suitable for
          startups experimenting with automation as well as large enterprises
          running mission-critical workloads.
        </p>

        <p className="font-['Avenir_LT_Std'] font-[350] text-[14px] sm:text-[15px] lg:text-[16px] leading-[26px] sm:leading-[28px] lg:leading-[30px] tracking-[0.06em] text-black">
          Security and compliance are embedded into the OCR Engine by design.
          Data is processed with strict isolation, encrypted in transit and at
          rest, and aligned with enterprise compliance requirements. The engine
          can be deployed in cloud, hybrid, or controlled environments depending
          on organizational constraints. This flexibility allows businesses to
          adopt advanced OCR capabilities without compromising governance,
          regulatory alignment, or internal security standards.
        </p>
      </div>
      <Footer />
    </div>
  );
};

export default OcrEngine;
